/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.agency;

import buyer.Customer;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import platform.TravelAgency;
import seller.Seat;
import service.Flight;
import vo.Ticket;

/**
 *
 * @author jrwang8
 */
public class ResultTicketJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TicketResultJPanel
     */
    TravelAgency travelAgency;
    JPanel userProcessContainer;
    Ticket ticket;
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd"); 

    
    public ResultTicketJPanel(TravelAgency travelAgency, Ticket ticket, JPanel userProcessContainer) {
        initComponents();
        this.travelAgency = travelAgency;
        this.userProcessContainer = userProcessContainer;
        this.ticket = ticket;
        
        populateDetail();
        
    }
    
    private void populateDetail() {
        Customer customer = this.ticket.getCustomer();
        Flight flight = this.ticket.getFlight();
        Seat seat = this.ticket.getSeat();
        
        lblCustomer.setText(customer.getCustomerName());
        lblFlight.setText(flight.getFlightId());
        lblPrice.setText(String.valueOf(flight.getPrice()));
        lblFrom.setText(flight.getFromCity());
        lblTo.setText(flight.getToCity());
        lblTime.setText(flight.getTime());
        lblDate.setText(sdf.format(flight.getDate()));
        lblSeat.setText(seat.getSeatId());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCustomer = new javax.swing.JLabel();
        lblFlight = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblFrom = new javax.swing.JLabel();
        lblTo = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblSeat = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();

        jLabel1.setText("Ticket Info");

        jLabel2.setText("Customer");

        jLabel3.setText("Flight");

        jLabel4.setText("Price");

        jLabel5.setText("From");

        jLabel6.setText("To");

        jLabel7.setText("Time");

        jLabel8.setText("Seat");

        jLabel9.setText("Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(314, 314, 314)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSeat)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTime)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(92, 92, 92)
                                .addComponent(lblDate))
                            .addComponent(lblTo)
                            .addComponent(lblFrom)
                            .addComponent(lblPrice)
                            .addComponent(lblFlight)
                            .addComponent(lblCustomer))))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblCustomer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblFlight))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lblPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(lblFrom))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblTo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblTime)
                    .addComponent(jLabel9)
                    .addComponent(lblDate))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblSeat))
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCustomer;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblFlight;
    private javax.swing.JLabel lblFrom;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblSeat;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTo;
    // End of variables declaration//GEN-END:variables
}
