/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.airliner;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import platform.TravelAgency;
import seller.Airliner;
import seller.Airplane;
import service.Flight;

/**
 *
 * @author jrwang8
 */
public class DetailAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailAirlinerJPanel
     */
    
    TravelAgency travelAgency;
    Airliner airliner;
    JPanel userProcessContainer;
    
    public DetailAirlinerJPanel(TravelAgency travelAgency, Airliner airliner, JPanel userProcessContainer) {
        initComponents();
        this.airliner = airliner;
        this.userProcessContainer = userProcessContainer;
        this.travelAgency = travelAgency;
        
        populateAirplaneTable();
        populateFlightTable();
        populateName();
    }
    
    private void populateName() {
        
        if(airliner == null) {
            return;
        }
        
        txtAirlinerName.setText(airliner.getAirlinerName());
    }
    
    private void populateAirplaneTable() {
        
        DefaultTableModel dtm = (DefaultTableModel)tblAirplane.getModel();
        dtm.setRowCount(0);
        
        for(Airplane airplane : airliner.showAllAirplane()) {
            Object[] row = new Object[3];
            row[0] = airplane;
            row[1] = airplane.isAssigned() ? "Assigned" : "Wait to be Assigned";
            row[2] = airplane.getTotalAvailableSeat();
            
            dtm.addRow(row);
        }
    }
    
    private void populateFlightTable() {
        
        DefaultTableModel dtm = (DefaultTableModel)tblFlight.getModel();
        dtm.setRowCount(0);
        
        for(Flight flight : airliner.showAllFlight()) {
            Object[] row = new Object[6];
            row[0] = flight;
            row[1] = flight.getFromCity();
            row[2] = flight.getToCity();
            row[3] = flight.getTime();
            row[4] = flight.getPrice();
            row[5] = flight.isAvailable() ? "Available" : "Not Available";
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlight = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAirplane = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAirlinerName = new javax.swing.JTextField();
        btnUpdateName = new javax.swing.JButton();
        btnSaveName = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnAddAirplane = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNewPlane = new javax.swing.JTextField();
        btnSavePlane = new javax.swing.JButton();
        btnAddFlight = new javax.swing.JButton();
        btnFlightDetail = new javax.swing.JButton();
        btnCancelFlight = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        tblFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Flight", "From", "To", "Time", "Price", "isAvailable"
            }
        ));
        jScrollPane1.setViewportView(tblFlight);
        if (tblFlight.getColumnModel().getColumnCount() > 0) {
            tblFlight.getColumnModel().getColumn(0).setPreferredWidth(150);
        }

        tblAirplane.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Airplane", "isAssigned", "AvailableSeats"
            }
        ));
        jScrollPane2.setViewportView(tblAirplane);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Airliner Details");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Airliner:");

        txtAirlinerName.setEnabled(false);

        btnUpdateName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnUpdateName.setText("UpdateName");
        btnUpdateName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateNameActionPerformed(evt);
            }
        });

        btnSaveName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSaveName.setText("SaveName");
        btnSaveName.setEnabled(false);
        btnSaveName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Airplane List");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("Flight List");

        btnAddAirplane.setText("Add Airplane");
        btnAddAirplane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirplaneActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Airplane");

        txtNewPlane.setEnabled(false);

        btnSavePlane.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnSavePlane.setText("comfirm");
        btnSavePlane.setEnabled(false);
        btnSavePlane.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePlaneActionPerformed(evt);
            }
        });

        btnAddFlight.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnAddFlight.setText("Add Flight");
        btnAddFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlightActionPerformed(evt);
            }
        });

        btnFlightDetail.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnFlightDetail.setText("Flight Detail");
        btnFlightDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlightDetailActionPerformed(evt);
            }
        });

        btnCancelFlight.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnCancelFlight.setText("Cancel Flight");
        btnCancelFlight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFlightActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(82, 82, 82))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(29, 29, 29)
                                        .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnUpdateName)
                                        .addGap(57, 57, 57)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtNewPlane, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnAddAirplane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSavePlane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAddFlight, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFlightDetail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancelFlight, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaveName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRefresh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel4)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAirlinerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateName)
                    .addComponent(btnSaveName))
                .addGap(10, 10, 10)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddAirplane)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtNewPlane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnSavePlane)))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddFlight)
                        .addGap(18, 18, 18)
                        .addComponent(btnFlightDetail)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelFlight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRefresh)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateNameActionPerformed
        // TODO add your handling code here:
        
        txtAirlinerName.setEnabled(true);
        btnSaveName.setEnabled(true);
        btnUpdateName.setEnabled(false);
        
    }//GEN-LAST:event_btnUpdateNameActionPerformed

    private void btnSaveNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveNameActionPerformed
        // TODO add your handling code here:
        
        String airlinerName = txtAirlinerName.getText();
        this.airliner.setAirlinerName(airlinerName);
        
        txtAirlinerName.setEnabled(false);
        btnSaveName.setEnabled(false);
        btnUpdateName.setEnabled(true);
        
    }//GEN-LAST:event_btnSaveNameActionPerformed

    private void btnAddAirplaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirplaneActionPerformed
        // TODO add your handling code here:
        
        txtNewPlane.setEnabled(true);
        btnSavePlane.setEnabled(true);
        btnAddAirplane.setEnabled(false);
        
    }//GEN-LAST:event_btnAddAirplaneActionPerformed

    private void btnSavePlaneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePlaneActionPerformed
        // TODO add your handling code here:
        
        String airplaneName = txtNewPlane.getText();
        if(airplaneName.equals("")) {
            JOptionPane.showMessageDialog(null, "Enter airplaneName");
            return;
        }
        
        this.airliner.addAirplaneById(airplaneName);
        
        txtNewPlane.setEnabled(false);
        btnSavePlane.setEnabled(false);
        btnAddAirplane.setEnabled(true);
        
        JOptionPane.showMessageDialog(null, "Success!");

        DetailAirlinerJPanel panel = new DetailAirlinerJPanel(this.travelAgency, this.airliner, userProcessContainer);
            
        userProcessContainer.add("DetailAirlinerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSavePlaneActionPerformed

    private void btnAddFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlightActionPerformed
        // TODO add your handling code here:
        
        CreateFlightJPanel panel = new CreateFlightJPanel(this.travelAgency, airliner, userProcessContainer);
        
        userProcessContainer.add("CreateFlightJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_btnAddFlightActionPerformed

    private void btnFlightDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlightDetailActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblFlight.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            Flight flight = (Flight) tblFlight.getValueAt(selectedRow, 0);
            DetailFlightJPanel panel = new DetailFlightJPanel(this.travelAgency, flight, userProcessContainer);
            userProcessContainer.add("DetailFlightJPanel", panel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        populateFlightTable();
    }//GEN-LAST:event_btnFlightDetailActionPerformed

    private void btnCancelFlightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFlightActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblFlight.getSelectedRow();
        if(selectedRow >= 0) {
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete?", "Warning", dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION) {
                Flight flight = (Flight) tblFlight.getValueAt(selectedRow, 0);
                flight.setAvailable(false);
                
                List<Flight> alllist = travelAgency.getOffice().getAllAvailableFlight();
                for(Flight f : alllist) {
                    if(f.getFlightId().equals(flight.getFlightId())) {
                        f.setAvailable(false);
                    }
                }
                
                populateFlightTable();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please selct", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        
    }//GEN-LAST:event_btnCancelFlightActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        
        DetailAirlinerJPanel panel = new DetailAirlinerJPanel(this.travelAgency, this.airliner, userProcessContainer);
            
        userProcessContainer.add("DetailAirlinerJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnRefreshActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddAirplane;
    private javax.swing.JButton btnAddFlight;
    private javax.swing.JButton btnCancelFlight;
    private javax.swing.JButton btnFlightDetail;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSaveName;
    private javax.swing.JButton btnSavePlane;
    private javax.swing.JButton btnUpdateName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAirplane;
    private javax.swing.JTable tblFlight;
    private javax.swing.JTextField txtAirlinerName;
    private javax.swing.JTextField txtNewPlane;
    // End of variables declaration//GEN-END:variables
}
